StylesPath = styles
MinAlertLevel = suggestion

[formats]
md = markdown

[_posts/*.md]
BasedOnStyles = StopSlop

# Ignore Jekyll frontmatter and liquid tags
BlockIgnores = (?s) *({%.*?%}), (?s) *({{.*?}})
