title: Abdul Aziz Zailani
description: Catatan & Opini seputar SRE, DevOps, dan Otomasi Infrastruktur.
url: "https://abdul-zailani.github.io"
theme: minima
# Konfigurasi sosial media bawaan Minima (opsional, akan tampil di footer)
twitter_username: aazizzailani
github_username: abdul-zailani

# Konfigurasi agar folder blog di-scan oleh jekyll sebagai posts
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: "blog"
    values:
      layout: "post"
